#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /api/login
  methods: ['POST']
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: ['POST']
