controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /login_check
    methods: ['POST']

register:
    path: /register
    methods: ['POST']
    defaults:
        _controller: App\Controller\UserController::new

current_user:
    path: /api/current-user
    methods: ['GET']
    defaults:
        _controller: App\Controller\UserController::current

ratings_by_contract:
    path: /api/ratings-by-contract/{contractId}
    methods: ['GET']
    controller: App\Controller\MissionController::getRatingsByContract
    # defaults:
        # _api_resource_class: App\Entity\User
        # _api_item_operation_name: post_publication
