#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: ['POST']
